CREATE TABLE [dbo].[Sys_User] (
    [User_Id]            INT             IDENTITY (1, 1) NOT NULL,
    [Role_Id]            INT             NOT NULL,
    [RoleName]           NVARCHAR (200)  NULL,
    [PhoneNo]            NVARCHAR (11)   NULL,
    [Remark]             NVARCHAR (200)  NULL,
    [Tel]                NVARCHAR (20)   NULL,
    [UserName]           NVARCHAR (100)  NOT NULL,
    [UserPwd]            NVARCHAR (200)  NULL,
    [UserTrueName]       NVARCHAR (20)   NOT NULL,
    [DeptName]           NVARCHAR (150)  NULL,
    [Dept_Id]            INT             NULL,
    [Email]              NVARCHAR (100)  NULL,
    [Enable]             TINYINT         NOT NULL,
    [Gender]             INT             NULL,
    [HeadImageUrl]       NVARCHAR (500)  NULL,
    [IsRegregisterPhone] INT             NULL,
    [LastLoginDate]      DATETIME        NULL,
    [LastModifyPwdDate]  DATETIME        NULL,
    [Address]            NVARCHAR (200)  NULL,
    [AppType]            INT             NULL,
    [AuditDate]          DATETIME        NULL,
    [AuditStatus]        INT             NULL,
    [Auditor]            NVARCHAR (200)  NULL,
    [OrderNo]            INT             NULL,
    [Token]              NVARCHAR (500)  NULL,
    [CreateID]           INT             NULL,
    [CreateDate]         DATETIME        NULL,
    [Creator]            NVARCHAR (200)  NULL,
    [Mobile]             NVARCHAR (100)  NULL,
    [Modifier]           NVARCHAR (200)  NULL,
    [ModifyDate]         DATETIME        NULL,
    [ModifyID]           INT             NULL,
    [DeptIds]            NVARCHAR (2000) NULL,
    [Employee_Number]    NVARCHAR (100)  NULL,
    CONSTRAINT [PK_Sys_User] PRIMARY KEY CLUSTERED ([User_Id] ASC)
);

