CREATE TABLE [dbo].[Sys_TableColumn] (
    [ColumnId]      INT            IDENTITY (1, 1) NOT NULL,
    [ApiInPut]      INT            NULL,
    [ApiIsNull]     INT            NULL,
    [ApiOutPut]     INT            NULL,
    [ColSize]       INT            NULL,
    [ColumnCNName]  NVARCHAR (100) NULL,
    [ColumnName]    NVARCHAR (100) NULL,
    [ColumnType]    NVARCHAR (MAX) NULL,
    [ColumnWidth]   INT            NULL,
    [Columnformat]  NVARCHAR (MAX) NULL,
    [CreateDate]    DATETIME       NULL,
    [CreateID]      INT            NULL,
    [Creator]       NVARCHAR (200) NULL,
    [DropNo]        NVARCHAR (50)  NULL,
    [EditColNo]     INT            NULL,
    [EditRowNo]     INT            NULL,
    [EditType]      NVARCHAR (200) NULL,
    [Enable]        INT            NULL,
    [IsColumnData]  INT            NULL,
    [IsDisplay]     INT            NULL,
    [IsImage]       INT            NULL,
    [IsKey]         INT            NULL,
    [IsNull]        INT            NULL,
    [IsReadDataset] INT            NULL,
    [Maxlength]     INT            NULL,
    [Modifier]      NTEXT          NULL,
    [ModifyDate]    DATETIME       NULL,
    [ModifyID]      INT            NULL,
    [OrderNo]       INT            NULL,
    [Script]        NTEXT          NULL,
    [SearchColNo]   INT            NULL,
    [SearchRowNo]   INT            NULL,
    [SearchType]    NVARCHAR (200) NULL,
    [Sortable]      INT            NULL,
    [TableName]     NVARCHAR (200) NULL,
    [Table_Id]      INT            NULL,
    CONSTRAINT [PK_Sys_TableColumn] PRIMARY KEY CLUSTERED ([ColumnId] ASC)
);

